### ISSUE TITLE
Erro ferramenta de seleção genérica

### ISSUE THREAD

**Issue by dinizime** [dsgoficial/DsgTools#190]
### Subject of the issue (Assunto do problema)
`AttributeError: 'NoneType' object has no attribute 'intersects' 
Traceback (most recent call last):
  File "C:/Users/diniz.1CGEO/.qgis2/python/plugins\DsgTools\ProductionTools\CopyPasteTool\multiLayerSelect.py", line 140, in canvasPressEvent
    self.createContextMenu(e)
  File "C:/Users/diniz.1CGEO/.qgis2/python/plugins\DsgTools\ProductionTools\CopyPasteTool\multiLayerSelect.py", line 305, in createContextMenu
    if feature.geometry().intersects(rect):
AttributeError: 'NoneType' object has no attribute 'intersects
Versão do Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
Versão do QGIS: 2.18.14 Las Palmas, ff83b9a479`

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional):  Windows 10
* version of QGIS (Versão do QGIS):  2.18.14
* version of DSGTools (Versão do DSGTools):  3.1 Dev

### Steps to reproduce (Passos para reproduzir)
Utilizando a ferramenta de seleção genérica e clicando em qualquer lugar do canvas da esse erro, não selecionando nenhuma feição.

**Comment by dinizime** [comment]
Resolvido
