### ISSUE TITLE
Erro ferramenta de circulo e angulo reto

### ISSUE THREAD

**Issue by dinizime** [dsgoficial/DsgTools#191]
### Subject of the issue (Assunto do problema)
`AttributeError: 'NoneType' object has no attribute 'lower' 
Traceback (most recent call last):
  File "C:/Users/diniz.1CGEO/.qgis2/python/plugins\DsgTools\ProductionTools\Acquisition\circle.py", line 53, in canvasReleaseEvent
    self.endGeometry()
  File "C:/Users/diniz.1CGEO/.qgis2/python/plugins\DsgTools\ProductionTools\Acquisition\circle.py", line 45, in endGeometry
    self.createGeometry(self.geometry)
  File "C:/Users/diniz.1CGEO/.qgis2/python/plugins\DsgTools\ProductionTools\Acquisition\geometricaAquisition.py", line 160, in createGeometry
    if self.getSuppressOptions(): #this is calculated every time because user can switch options while using tool
  File "C:/Users/diniz.1CGEO/.qgis2/python/plugins\DsgTools\ProductionTools\Acquisition\geometricaAquisition.py", line 28, in getSuppressOptions
    if setting.lower() == u'false':
AttributeError: 'NoneType' object has no attribute 'lower'
Versão do Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
Versão do QGIS: 2.18.14 Las Palmas, ff83b9a479 `

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional): Windows 10
* version of QGIS (Versão do QGIS):  2.18.14
* version of DSGTools (Versão do DSGTools):  3.1 Dev

### Steps to reproduce (Passos para reproduzir)
Ao finalizar a aquisição utilizando a ferramenta de ângulos retos e circulo causa o erro python.

**Comment by phborba** [comment]
@dinizime acho que resolvi no commit #191

Pode verificar pra mim por favor?

**Comment by dinizime** [comment]
Resolvido
