### ISSUE TITLE
Erro seletor genérico + Raster

### ISSUE THREAD

**Issue by dinizime** [dsgoficial/DsgTools#243]
### Subject of the issue (Assunto do problema)
AttributeError: 'QgsRasterLayer' object has no attribute 'selectedFeatures' 
Traceback (most recent call last):
  File "C:/Users/diniz.1CGEO/.qgis2/python/plugins\DsgTools\ProductionTools\CopyPasteTool\multiLayerSelect.py", line 167, in canvasPressEvent
    self.createContextMenu(e)
  File "C:/Users/diniz.1CGEO/.qgis2/python/plugins\DsgTools\ProductionTools\CopyPasteTool\multiLayerSelect.py", line 439, in createContextMenu
    layerList = self.getPrimitiveDict(e, hasControlModifyer=selected)
  File "C:/Users/diniz.1CGEO/.qgis2/python/plugins\DsgTools\ProductionTools\CopyPasteTool\multiLayerSelect.py", line 194, in getPrimitiveDict
    firstGeom = self.checkSelectedLayers()
  File "C:/Users/diniz.1CGEO/.qgis2/python/plugins\DsgTools\ProductionTools\CopyPasteTool\multiLayerSelect.py", line 368, in checkSelectedLayers
    selection = layer.selectedFeatures()
AttributeError: 'QgsRasterLayer' object has no attribute 'selectedFeatures'

Versão do Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
Versão do QGIS: 2.18.14 Las Palmas, ff83b9a479 

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional):  Windows 10
* version of QGIS (Versão do QGIS): 2.18.14
* version of DSGTools (Versão do DSGTools): 3.2_dev

### Steps to reproduce (Passos para reproduzir)
Utilizar a ferramenta seletor genérico com um raster de fundo produz erro python

**Comment by phborba** [comment]
Acho que foi finalizado no commit 8bd8334b5c6332578ba8dd409cdc1511b0b07fe9

@dinizime pode testar por favor?

**Comment by phborba** [comment]
resolvido no commit f58ef6a44a50ac628bc8890b8ff09eb5df7188c2

@dinizime você pode ver pra mim por favor? Nesse commit veio a ferramenta de tooltip no raster
