### ISSUE TITLE
Identificar gaps e sobreposição na cobertura terrestre com bugs

### ISSUE THREAD

**Issue by rsmaior** [dsgoficial/DsgTools#380]
### Subject of the issue (Assunto do problema)
No sistema Kubuntu o processo Identificar gaps e sobreposição na cobertura terrestre não está rodando.

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional): Kubuntu 16.04 e 18.04 (versão 64 bits)
* version of QGIS (Versão do QGIS):  3.4.3
* version of DSGTools (Versão do DSGTools): 4.0 do branch de migração para o QGIS3 (commit 562e15b2f4e9835c96771433baf4a5de49140bc3)

### Steps to reproduce (Passos para reproduzir)
Basta rodar o processo no kubuntu, selecionando as camadas da cobertura como entrada. Os outros parâmetros, como arquivo de saida, abrir saida no QGIS etc foram testados e geraram o mesmo resultado

### Expected behaviour (Comportamento esperado)
Identificar os gaps e sobreposição

### Actual behaviour (Comportamento atual)
Falha crítica.

Mensagem de erro: 

```
2019-02-28T14:43:11     CRITICAL    Traceback (most recent call last):
              File "/home/rodrigo/apps/qgis-3.4.3/build-master/output/python/plugins/processing/algs/grass7/Grass7Algorithm.py", line 413, in processAlgorithm
              Grass7Utils.executeGrass(self.commands, feedback, self.outputCommands)
              File "/home/rodrigo/apps/qgis-3.4.3/build-master/output/python/plugins/processing/algs/grass7/Grass7Utils.py", line 373, in executeGrass
              startupinfo=si if isWindows() else None
             TypeError: __init__() got an unexpected keyword argument 'encoding'
             
2019-02-28T14:43:11     CRITICAL    There were errors executing the algorithm.
2019-02-28T14:43:11     CRITICAL    Traceback (most recent call last):
              File "/home/rodrigo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DsgTools/core/DSGToolsProcessingAlgs/Algs/ValidationAlgs/identifyGapsAndOverlapsInCoverageAlgorithm.py", line 104, in processAlgorithm
              lyr = self.overlayCoverage(coverage, context)
              File "/home/rodrigo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DsgTools/core/DSGToolsProcessingAlgs/Algs/ValidationAlgs/identifyGapsAndOverlapsInCoverageAlgorithm.py", line 131, in overlayCoverage
              x = processing.run('grass7:v.overlay', parameters, context = context)
              File "/home/rodrigo/apps/qgis-3.4.3/build-master/output/python/plugins/processing/tools/general.py", line 96, in run
              return Processing.runAlgorithm(algOrName, parameters, onFinish, feedback, context)
              File "/home/rodrigo/apps/qgis-3.4.3/build-master/output/python/plugins/processing/core/Processing.py", line 183, in runAlgorithm
              raise QgsProcessingException(msg)
             _core.QgsProcessingException: There were errors executing the algorithm.
```

**Comment by rsmaior** [comment]
### Subject of the issue (Assunto do problema)
No sistema Windows 7 o processo Identificar gaps e sobreposição na cobertura terrestre roda, porém:
a) Sem colocar a moldura como camada opcional de referência: não identifica qualquer buraco ou sobreposição
b) Colocando a moldura como camada opcional de referência: Identifica a região inteira da moldura como gap, com excessão de uma área de barragem

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional): Windows 7  64 bits
* version of QGIS (Versão do QGIS):  3.4.4
* version of DSGTools (Versão do DSGTools): 4.0 do branch de migração para o QGIS3 (commit 562e15b2f4e9835c96771433baf4a5de49140bc3)

### Steps to reproduce (Passos para reproduzir)
Basta rodar o processo no Windows, selecionando as camadas da cobertura como entrada com e sem a moldura como referência. Testei em três bancos de dados no servidor 10.1.10.130, o banco capacitacao_QGIS_cavalcanti, banco capacitacao_QGIS_wodson e m2260_1_se_cif.

### Expected behaviour (Comportamento esperado)
Identificar os gaps e sobreposição

### Actual behaviour (Comportamento atual)
a) Sem a moldura como camada opcional de referência: não identifica qualquer buraco ou sobreposição
b) Com a moldura como camada opcional de referência: Identifica a região inteira da moldura como gap, com excessão de uma área de barragem (printscreen anexo ilustra o resultado)
![tela](https://user-images.githubusercontent.com/11916280/53589328-df93f300-3b6d-11e9-934c-4c62bbc3c938.png)

**Comment by phborba** [comment]
@rsmaior atualiza os qgis para a 3.4.5 por favor, que acho que eles resolveram os problemas específicos do GRASS.

**Comment by rsmaior** [comment]
Não resolveu. 

Possivelmente tem algo a ver com
https://issues.qgis.org/issues/20886
https://www.mail-archive.com/qgis-user@lists.osgeo.org/msg42043.html

Talvez?

**Comment by jpesperidiao** [comment]
Resolvido no commit [233f494](https://github.com/dsgoficial/DsgTools/commit/233f4948b796426c3ce8594d4874f0fb7ded0da1).
