### ISSUE TITLE
Bug Visualizar Codelist e valores

### ISSUE THREAD

**Issue by dinizime** [dsgoficial/DsgTools#383]
Ao utilizar a ferramenta de Visualizar Codelist e valores com a edgv pro o seguinte erro ocorre: 

`NameError: name 'Qgis' is not defined 
Traceback (most recent call last):
  File "C:/Users/diniz.1CGEO/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DsgTools\gui\ProductionTools\Toolboxes\AttributeTools\code_list.py", line 248, in on_refreshButton_clicked
    self.loadCodeList()
  File "C:/Users/diniz.1CGEO/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DsgTools\gui\ProductionTools\Toolboxes\AttributeTools\code_list.py", line 184, in loadCodeList
    for code, value in valueDict.items():
AttributeError: 'list' object has no attribute 'items'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/diniz.1CGEO/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DsgTools\gui\ProductionTools\Toolboxes\AttributeTools\code_list.py", line 251, in on_refreshButton_clicked
    QgsMessageLog.logMessage(self.tr('Error loading classes to Code List Viewer: ')+':'.join(e.args), "DSG Tools Plugin", Qgis.Critical)
NameError: name 'Qgis' is not defined`

Windows 10
DSGTools 4

**Comment by jpesperidiao** [comment]
O Code List foi refatorado há pouco tempo, creio que o problema foi resolvido. Se puder confirmar, @dinizime, aguardarei para finalizar o ticket!
