### ISSUE TITLE
DSGtool 4.0 conflitting with Qgis2Web 3.16

### ISSUE THREAD

**Issue by yjmenezes** [dsgoficial/DsgTools#503]
DSGtool 4.0 conflitting with Qgis2Web 3.16

Debian GNU/Linux 10.x,  QGIS 3.14-Pi
QGIS  3.14.16-Pi   commit  a235a149f0

Installing only  DSGtoll and DSGtoolsOP, both runs ok, but after install Qgis2Web 3.16, i get this messages:

Impossível carregar complemento 'DsgTools' Devido a um erro ao chamar o método Class Factory(). 
TypeError: qRegisterResourceData(int, bytes, bytes, bytes): argument 2 has unexpected type 'str' 

    qInitResources()
  File "/home/jmenezes/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/resources_rc.py", line 1243, in qInitResources
    qt_resource_name, qt_resource_data)
TypeError: qRegisterResourceData(int, bytes, bytes, bytes): argument 2 has unexpected type 'str'

Versão do Python: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0] 
Versão do QGIS: 3.14.16-Pi Pi, a235a149f0 

ERROR:
DSGtools stop loading
Qgis2web  runs fine

thank you DSG team.

**Comment by jpesperidiao** [comment]
Bom dia, @yjmenezes. Iremos verificar o problema e atualizações serão postadas por aqui mesmo. Obrigado pela contribuição!

**Comment by jpesperidiao** [comment]
Bom dia, @yjmenezes,

sobre o problema apontado, não consegui reproduzir o problema.

O OS que usamos é o Ubuntu/Kubuntu (bem mais comum a 2ª versão), então não foi utilizado o Debian.

Testei os dois em conjunto na LTR ('A Coruña' 3.10) e na em um versão dev do QGIS recente, da semana passada (3.15).

A princípio, funcionou normal (Teve um erro levantado mas foi do próprio qgis2web):

```python
AttributeError: type object 'RenderUnit' has no attribute 'RenderPoints' 
Traceback (most recent call last):
  File ":/~QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 337, in previewMap
    preview_file = self.createPreview()
  File ":/~QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 300, in createPreview
    dest_folder=utils.tempFolder()).index_file
  File ":/~QGIS/QGIS3/profiles/default/python/plugins/qgis2web/mapboxWriter.py", line 104, in write
    folder=dest_folder)
  File ":/~QGIS/QGIS3/profiles/default/python/plugins/qgis2web/mapboxWriter.py", line 294, in writeMapbox
    useOSMB, vtSources, layers)
  File ":/~QGIS/QGIS3/profiles/default/python/plugins/qgis2web/mapboxLayerScripts.py", line 145, in writeVectorLayer
    mblayers = getLayerStyle(layer)
  File ":/~QGIS/QGIS3/profiles/default/python/plugins/qgis2web/mapboxStyleScripts.py", line 43, in getLayerStyle
    mapboxStyle = bridgestyle.qgis.layerStyleAsMapbox(layer)
  File ":/~QGIS/QGIS3/profiles/default/python/plugins/qgis2web/bridgestyle/qgis/__init__.py", line 50, in layerStyleAsMapbox
    geostyler, icons, warnings = togeostyler.convert(layer)
  File ":/~QGIS/QGIS3/profiles/default/python/plugins/qgis2web/bridgestyle/qgis/togeostyler.py", line 32, in convert
    geostyler = processLayer(layer)
  File ":/~QGIS/QGIS3/profiles/default/python/plugins/qgis2web/bridgestyle/qgis/togeostyler.py", line 76, in processLayer
    rules.extend(processRule(rule, None, layer.opacity(), layer))
  File ":/~QGIS/QGIS3/profiles/default/python/plugins/qgis2web/bridgestyle/qgis/togeostyler.py", line 453, in processRule
    symbolizers = _createSymbolizers(rule.symbol(), layerOpacity)
  File ":/~QGIS/QGIS3/profiles/default/python/plugins/qgis2web/bridgestyle/qgis/togeostyler.py", line 605, in _createSymbolizers
    symbolizer = _createSymbolizer(sl, opacity)
  File ":/~QGIS/QGIS3/profiles/default/python/plugins/qgis2web/bridgestyle/qgis/togeostyler.py", line 625, in _createSymbolizer
    symbolizer = _simpleFillSymbolizer(sl, opacity)
  File ":/~QGIS/QGIS3/profiles/default/python/plugins/qgis2web/bridgestyle/qgis/togeostyler.py", line 936, in _simpleFillSymbolizer
    sl, "outline_width", QgsSymbolLayer.PropertyStrokeWidth
  File ":/~QGIS/QGIS3/profiles/default/python/plugins/qgis2web/bridgestyle/qgis/togeostyler.py", line 572, in _symbolProperty
    v = _handleUnits(v, units, propertyConstant)
  File ":/~QGIS/QGIS3/profiles/default/python/plugins/qgis2web/bridgestyle/qgis/togeostyler.py", line 519, in _handleUnits
    if units in ["Point", QgsUnitTypes.RenderUnit.RenderPoints]:
AttributeError: type object 'RenderUnit' has no attribute 'RenderPoints'
```

Este erro foi identificado quando tentamos usar a opção "Mapbox GL JS" para atualizar o _preview_.

Você poderia dar mais detalhes de como reproduzir o problema?

**Comment by jpesperidiao** [comment]
A princípio, não há problemas de funcionamento do DSGTools. Assim, vou encerrar o _issue_, mas, caso haja maior detalhamento e um algum mal-funcionamento do nosso _plugin_ que não tenha compreendido / testado correntamente, é só informar por aqui que reabriremos e invetigaremos mais a fundo.
