### ISSUE TITLE
Couldn't load plugin 'DsgTools' 

### ISSUE THREAD

**Issue by HumbertoDiego** [dsgoficial/DsgTools#631]
### Subject of the issue (Assunto do problema)
Plugin DSGTools não é carregado se Plugin Qgis2web também estiver instalado. Resolvido desabilitando o qgis2web.

### Your environment (Seu ambiente)
* Ubuntu 20.04.4 LTS
* Python version: 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0] 
* QGIS version: 3.24.0-Tisler Tisler, 6b44a42058 
* version of DSGTools (Versão do DSGTools): 

### Steps to reproduce (Passos para reproduzir)
Ubuntu 18 --> upgrade Ubuntu 20 --> instalar o QGIS pelo repositŕoio oficial --> instalar os Plugins qgis2web, DSGTools e DSG Tools Op

### Expected behaviour (Comportamento esperado)
Não aparecer msg de erro

### Actual behaviour (Comportamento atual)
Couldn't load plugin 'DsgTools' 

TypeError: qRegisterResourceData(int, bytes, bytes, bytes): argument 2 has unexpected type 'str' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 401, in loadPlugin
    __import__(packageName)
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/capdiego/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DsgTools/__init__.py", line 25, in 
    from .dsg_tools import DsgTools
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/capdiego/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DsgTools/dsg_tools.py", line 47, in 
    from .gui.guiManager import GuiManager
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/capdiego/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DsgTools/gui/guiManager.py", line 34, in 
    from .ProductionTools.productionToolsGuiManager import ProductionToolsGuiManager
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/capdiego/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DsgTools/gui/ProductionTools/productionToolsGuiManager.py", line 26, in 
    from .Toolboxes.toolBoxesGuiManager import ToolBoxesGuiManager
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/capdiego/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DsgTools/gui/ProductionTools/Toolboxes/toolBoxesGuiManager.py", line 34, in 
    from .QualityAssuranceToolBox.qualityAssuranceDockWidget import QualityAssuranceDockWidget
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/capdiego/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DsgTools/gui/ProductionTools/Toolboxes/QualityAssuranceToolBox/qualityAssuranceDockWidget.py", line 42, in 
    from DsgTools.gui.ProductionTools.Toolboxes.QualityAssuranceToolBox\
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/capdiego/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DsgTools/gui/ProductionTools/Toolboxes/QualityAssuranceToolBox/workflowSetupDialog.py", line 45, in 
    FORM_CLASS, _ = uic.loadUiType(
  File "/usr/lib/python3/dist-packages/qgis/PyQt/uic/__init__.py", line 36, in __loadUiType
    return __PyQtLoadUiType(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/__init__.py", line 203, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "", line 80, in 
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/capdiego/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DsgTools/gui/CustomWidgets/OrderedPropertyWidgets/orderedTableWidget.py", line 37, in 
    FORM_CLASS, _ = uic.loadUiType(
  File "/usr/lib/python3/dist-packages/qgis/PyQt/uic/__init__.py", line 36, in __loadUiType
    return __PyQtLoadUiType(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/__init__.py", line 203, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "", line 102, in 
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/capdiego/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/resources_rc.py", line 1251, in 
    qInitResources()
  File "/home/capdiego/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/resources_rc.py", line 1242, in qInitResources
    QtCore.qRegisterResourceData(0x01, qt_resource_struct,
TypeError: qRegisterResourceData(int, bytes, bytes, bytes): argument 2 has unexpected type 'str'

Python Path:
~/.local/share/QGIS/QGIS3/profiles/default/python/plugins/lftools
/usr/share/qgis/python
~/.local/share/QGIS/QGIS3/profiles/default/python
~/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/usr/local/lib/python3.8/dist-packages
/usr/lib/python3/dist-packages
~/.local/share/QGIS/QGIS3/profiles/default/python
~/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DigitizingTools/tools
~/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DigitizingTools/tools
~/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DigitizingTools
~/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web
~/.local/share/QGIS/QGIS3/profiles/default/python/plugins
~/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DsgTools
~/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DsgTools

**Comment by HumbertoDiego** [comment]
version of DSGTools (Versão do DSGTools):
Installed version	[4.3.0]
