### ISSUE TITLE
qRegisterResourceData(int, bytes, bytes, bytes): argument 2 has unexpected type 'str'  Traceback (most recent call last):

### ISSUE THREAD

**Issue by VlamirNogueira** [dsgoficial/DsgTools#800]
O DGSTools apresenta o seguinte erro assim que carregado: 
.
Impossível carregar complemento 'DsgTools' 

TypeError: qRegisterResourceData(int, bytes, bytes, bytes): argument 2 has unexpected type 'str' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 401, in loadPlugin
    __import__(packageName)
  File "C:\Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DsgTools\__init__.py", line 25, in 
    from .dsg_tools import DsgTools
  File "C:\Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DsgTools\dsg_tools.py", line 38, in 
    from .gui.guiManager import GuiManager
  File "C:\Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DsgTools\gui\guiManager.py", line 34, in 
    from .ProductionTools.productionToolsGuiManager import ProductionToolsGuiManager
  File "C:\Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DsgTools\gui\ProductionTools\productionToolsGuiManager.py", line 26, in 
    from .Toolboxes.toolBoxesGuiManager import ToolBoxesGuiManager
  File "C:\Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DsgTools\gui\ProductionTools\Toolboxes\toolBoxesGuiManager.py", line 36, in 
    from .QualityAssuranceToolBox.qualityAssuranceDockWidget import (
  File "C:\Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DsgTools\gui\ProductionTools\Toolboxes\QualityAssuranceToolBox\qualityAssuranceDockWidget.py", line 49, in 
    from DsgTools.gui.ProductionTools.Toolboxes.QualityAssuranceToolBox.workflowSetupDialog import (
  File "C:\Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DsgTools\gui\ProductionTools\Toolboxes\QualityAssuranceToolBox\workflowSetupDialog.py", line 53, in 
    FORM_CLASS, _ = uic.loadUiType(
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\PyQt\uic\__init__.py", line 36, in __loadUiType
    return __PyQtLoadUiType(*args, **kwargs)
  File "C:\PROGRA~1\QGIS33~1.2\apps\Python39\lib\site-packages\PyQt5\uic\__init__.py", line 204, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "", line 79, in 
  File "C:\Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DsgTools\gui\CustomWidgets\OrderedPropertyWidgets\orderedTableWidget.py", line 40, in 
    FORM_CLASS, _ = uic.loadUiType(
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\PyQt\uic\__init__.py", line 36, in __loadUiType
    return __PyQtLoadUiType(*args, **kwargs)
  File "C:\PROGRA~1\QGIS33~1.2\apps\Python39\lib\site-packages\PyQt5\uic\__init__.py", line 204, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "", line 102, in 
  File "C:\Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\resources_rc.py", line 1251, in 
    qInitResources()
  File "C:\Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\resources_rc.py", line 1242, in qInitResources
    QtCore.qRegisterResourceData(0x01, qt_resource_struct,
TypeError: qRegisterResourceData(int, bytes, bytes, bytes): argument 2 has unexpected type 'str'

Versão do Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Versão do QGIS: 3.30.2-'s-Hertogenbosch 's-Hertogenbosch, 0992b533 

Caminho do Python:
C:\Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lftools
C:\Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HTML_Generator-main
C:\Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoINCRA
C:\Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\contour
C:/PROGRA~1/QGIS33~1.2/apps/qgis/./python
C:/Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~1.2/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS33~1.2\apps\grass\grass82\etc\python
C:\WINDOWS\system32
C:\Program Files\QGIS 3.30.2\bin\python39.zip
C:\PROGRA~1\QGIS33~1.2\apps\Python39\DLLs
C:\PROGRA~1\QGIS33~1.2\apps\Python39\lib
C:\Program Files\QGIS 3.30.2\bin
C:\Users\Usuário\AppData\Roaming\Python\Python39\site-packages
C:\PROGRA~1\QGIS33~1.2\apps\Python39
C:\PROGRA~1\QGIS33~1.2\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS33~1.2\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.2\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.2\apps\Python39\lib\site-packages\Pythonwin
C:/Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\Usuário\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools
C:\Users\Usuário\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools
C:\Users\Usuário\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows
C:\Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\excel_sync\libs\xlrd-1.2.0-py2.py3-none-any.whl
C:\Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\excel_sync\libs\xlwt-1.3.0-py2.py3-none-any.whl
C:\Users\Usuário\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\HCMGIS/forms
C:\Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\inde
C:\Users\Usuário\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\kmltools\libs
C:\Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web
C:\Users\Usuário\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
C:\Users/Usuário/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\rvt-qgis
C:\Users\Usuário\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DsgTools
C:\Users\Usuário\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DsgTools

**Comment by phborba** [comment]
Boa noite tudo bem?

Qual é o seu sistema operacional @VlamirNogueira , a versão do QGIS e a versão do DSGTools?

**Comment by phborba** [comment]
Como não houve mais feedback, vou fechar o issue, caso o problema persista, favor reabrir o issue.
